In [37]:
!pip install pyedflib


     |████████████████████████████████| 1.2MB 8.9MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for pyedflib: filename=pyEDFlib-0.1.20-cp36-cp36m-linux_x86_64.whl size=928467 sha256=7374685aba411605a023ff0d83cda4f7ebc869af693fd0fd5f827c0f2eb05bfe
  Stored in directory: /root/.cache/pip/wheels/0d/be/b5/574f8b99ad9ac2ecf78e0c5271040b5aff999febfe655b97a4
Successfully built pyedflib


In [43]:
import pyedflib
from datetime import datetime
import numpy as np

In [62]:





file_name = 'record-206232_20200911.edf'  #make sure file is in current directory
reader =pyedflib.EdfReader("record-206232_20200911.edf")
frequencies = reader.getSampleFrequencies()

# you can get the metadata included in the file and a list of all channels:


frequencies

OSError: ignored

In [56]:

#Manually enter start date and seizure date 

start_date = datetime(2020, 9, 11, 15, 17, 8, 520) # Get this exact value from the hexoskin website chart
sz_date = datetime(2020, 9, 11, 21, 18, 9, 926)
sz_onset_sec = (sz_date-start_date).total_seconds()

# Find the onset of the seizure in sec
sz_onset_sec = (sz_date-start_date).total_seconds()


# Find the onset of the seizure in datapoint for each modality

sz_onset_dp_ECG = sz_onset_sec*frequencies.item(0);
sz_onset_dp_Resp = sz_onset_sec*frequencies.item(3);
sz_onset_dp_Acc = sz_onset_sec*frequencies.item(6);





In [74]:
# Select a window centered around electrical seizure onset 
win_start = 1 ; # time in minute before seizure onset 
win_end = 3 ; # time in minute after seizure onset 

# Find window start and length for each Modality

win_start_dp_ECG= sz_onset_dp_ECG - (win_start*frequencies.item(0)*60)
win_length_dp_ECG =  (win_end*frequencies.item(0)*60);


window_ECG = reader.readSignal(0,win_start_dp_ECG,win_length_dp_ECG)


win_start_dp_Resp= sz_onset_dp_Resp - (win_start*frequencies.item(3)*60)
win_length_dp_Resp =  (win_end*frequencies.item(3)*60)-1
window_Resp = reader.readSignal(3,win_start_dp_Resp,win_length_dp_Resp)



win_start_dp_Acc= sz_onset_dp_Acc - (win_start*frequencies.item(3)*60)
win_length_dp_Acc =  (win_end*frequencies.item(6)*60)-1
window_Acc = reader.readSignal(0,win_start_dp_Acc,win_length_dp_Acc)


# Select Signals of Interest and Create a supblot 

# Extract Physiological Signals 

ecg = reader.readSignal(0,win_start_dp_ECG,win_length_dp_ECG)

respThor = reader.readSignal(3,win_start_dp_Resp,win_length_dp_ECG)
respAbd =reader.readSignal(4,win_start_dp_Resp,win_length_dp_ECG)

AccY =reader.readSignal(6,win_start_dp_ECG,win_length_dp_ECG)
AccY =reader.readSignal(7,win_start_dp_ECG,win_length_dp_ECG)
AccY =reader.readSignal(8,win_start_dp_ECG,win_length_dp_ECG)




5529600.001536
46080
read -1, less than 46080 requested!!!
46080
[0. 0. 0. ... 0. 0. 0.]
read -1, less than 23039 requested!!!
[0. 0. 0. ... 0. 0. 0.]
read -1, less than 23039 requested!!!
[0. 0. 0. ... 0. 0. 0.]
